### PR TITLE
Add "channel" test case of having messages

### PR DESCRIPTION
**Pull request by smallbee3**
## Description
Add "channel" test case of having messages after the pull request of mutation 'createMessage' 

## Related Pullrequest
#63 

## CheckList
- [x] I read the Contributor Guide and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] Run yarn lint && yarn tsc
- [x] I am willing to follow-up on review comments in a timely manner.

### CODE REVIEW

**Comment by hyochan** [comment]
@smallbee3 Would you like to keep working on this? #70 has been merged so I think you would feel sufficient with continuing this.

**Comment by smallbee3** [comment]
@hyochan 
Wow, did you already finish refactoring "createChannel" & "createMessage" mutations?
If those mutations are finished, then I can refactor this test code as you said.

Do you want me to do this work again till next meetup?

**Comment by hyochan** [comment]
> @hyochan
> Wow, did you already finish refactoring "createChannel" & "createMessage" mutations?
> You are the man of performance!
> If those mutations are finished, then I can refactor this test code as you said.
> 
> Ok. I'll make this test done again till next meetup.

If you have time it would be promising :)

**Comment by hyochan** [comment]
Closes via #71

**Pull request closed without merging**
